seqs_root: F:\AI
sequences: 
  -
    seq_name: test_chejian
    # seq_name: test_countyard
    # seq_name: test_parking
states: 
      - 
        expo_t: 200
        gain: 1
      - 
        expo_t: 400
        gain: 1
      - 
        expo_t: 1000
        gain: 1
      - 
        expo_t: 5000
        gain: 1
      - 
        expo_t: 20000
        gain: 1
